services:
  web:
    build:
      context: .
      args:
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
    networks:
      - dokploy-network
    command: npm run start
    env_file:
      - .env
    restart: unless-stopped
    # Add labels to services that users will hit with Traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sailnex.rule=Host(`sailnex.com`)"
      - "traefik.http.routers.sailnex.entrypoints=websecure"
      - "traefik.http.routers.sailnex.tls.certResolver=letsencrypt"
      - "traefik.http.services.sailnex.loadbalancer.server.port=4001"

networks:
  dokploy-network:
    external: true
